export type HomeLocale = "en" | "zh";

export const homepageCopy = {
  en: {
    nav: { docs: "Documentation", locale: "中文", theme: "Switch color theme" },
    hero: {
      release: "Latest release",
      title: ["The ", "one data index", " for your agentic applications"],
      body: "Graph, vector, and full-text retrieval over the same transactional data—embedded in your application or running behind a service.",
      start: "Get started",
      docs: "Documentation",
      blog: "Blog",
    },
    foundation: {
      label: "Data foundation",
      title: "A transactional data foundation",
      body: "NeuG manages data before it indexes it. A graph-native engine owns schema, transactions, persistence, and recovery—so every retrieval path starts from one consistent state.",
      features: [
        ["Cypher-native", "Query language", "Define, mutate, and query connected data directly in its native model."],
        ["ACID", "Transactions", "Keep reads and writes consistent as application state changes."],
        ["Two modes", "Embedded · Service", "Run in-process or expose the same data engine behind a service."],
        ["Extensible", "Extension system", "Add new capabilities through extensions while keeping the core focused."],
        ["Apache 2.0", "Open source", "Use, modify, and distribute NeuG under the Apache 2.0 license."],
      ],
    },
    retrieval: {
      label: "Unified retrieval",
      title: "Three indexes. One result",
      body: "Query structure, semantics, and exact keywords together. NeuG ranks one result set without moving data across engines.",
      query: "Query",
      items: [
        ["Structure", "MATCH (:Service {name: 'PaymentService'})-[r]-(n) RETURN n"],
        ["Vector", "MATCH (n) RETURN n ORDER BY vector_distance_cosine(n.vec, $q) LIMIT 10"],
        ["Full-text", "MATCH (n) RETURN n ORDER BY bm25(n.text, 'retry timeout') LIMIT 10"],
      ],
      result: "Ranked result",
    },
    algorithms: {
      label: "Graph algorithms",
      title: "Analyze the graph in place",
      body: "Retrieval finds relevant entities. Graph algorithms reveal importance, communities, and patterns across the wider structure.",
      pagerankTitle: "Reveal influence",
      pagerankBody: "See which entities matter most across the graph.",
      leidenTitle: "Reveal communities",
      leidenBody: "See how connected entities organize into coherent communities.",
      moreTitle: "Beyond PageRank and Leiden",
      moreBody: "Run a broader set of graph algorithms over the same data.",
      moreLink: "Explore graph algorithms →",
      carried: "The same graph data as the retrieval example above",
      communities: ["Community A", "Community B", "Community C"],
    },
    why: {
      label: "Why NeuG",
      title: "Choose the right architecture",
      body: "Compare NeuG in the deployment mode that fits your workload—or against the multi-engine stack it can simplify.",
      tabs: ["NeuG vs graph databases", "One index vs a stitched stack"],
      graph: {
        facts: [
          ["Service · 50.6× throughput", "617 QPS for NeuG vs 12.2 QPS for Neo4j across 14 LDBC SNB Interactive complex reads."],
          ["Embedded · faster on 8 of 9", "Single-threaded NeuG beat LadybugDB's best multi-threaded result on eight of nine LSQB queries."],
          ["One engine, two deployment modes", "Run in-process for low-overhead analytics, or expose the same runtime as a service for concurrent workloads."],
        ],
        note: "REPRODUCIBLE DUAL-MODE BENCHMARK",
        methodology: "LDBC SNB SF1 · Apple Silicon · read workloads. Service test: 4 clients for 300 seconds.",
        link: "View methodology →",
      },
      stack: {
        facts: [
          ["Store entity data once", "Avoid replicating the same entities into three independently operated databases."],
          ["Fuse inside one engine", "Combine structure, vector similarity, and BM25 without cross-engine network hops or result joins."],
          ["One consistency boundary", "Graph, vector, and full-text indexes stay aligned with the same transactional data."],
        ],
      },
    },
    quick: {
      label: "Quick start",
      title: "From install to first query",
      body: "NeuG runs where your application runs. Install the library, open a database, and query it with Cypher.",
      compatibility: "Compatibility",
      groups: [
        ["Data formats", "Apache Arrow · Parquet"],
        ["Object storage", "S3 · OSS"],
        ["Operating systems", "Linux · macOS"],
        ["Architectures", "x86_64 · ARM64"],
      ],
      roadmap: "Windows · Roadmap",
    },
    close: ["One index. Fewer moving parts", "Start embedded. Move behind a service when your application needs it."],
    footer: "The one data index for your agentic applications.",
  },
  zh: {
    nav: { docs: "文档", locale: "EN", theme: "切换颜色主题" },
    hero: {
      release: "最新版本",
      title: ["面向你的 Agent 应用的", "全能数据索引", ""],
      body: "在同一份事务数据上统一提供图、向量与全文检索——既可嵌入应用，也可作为服务运行。",
      start: "开始使用",
      docs: "查看文档",
      blog: "博客",
    },
    foundation: {
      label: "数据底座",
      title: "事务数据底座",
      body: "NeuG 先管理数据，再建立索引。图原生引擎统一负责模式、事务、持久化与恢复，让每一条检索路径都从同一份一致状态出发。",
      features: [
        ["原生 Cypher", "查询语言", "直接以原生模型定义、更新和查询相互连接的数据。"],
        ["ACID", "事务", "应用状态持续变化时，始终保持读写一致。"],
        ["两种模式", "嵌入式 · 服务", "既可在进程内运行，也可将同一数据引擎部署为服务。"],
        ["可扩展", "扩展机制", "通过扩展持续加入新能力，同时保持核心引擎专注轻量。"],
        ["Apache 2.0", "开源协议", "遵循 Apache 2.0 许可证，可使用、修改和分发 NeuG。"],
      ],
    },
    retrieval: {
      label: "统一检索",
      title: "三种索引，一个结果",
      body: "同时查询结构、语义与精确关键词。NeuG 直接生成统一排序结果，无需在多个引擎间搬运数据。",
      query: "查询",
      items: [
        ["结构", "MATCH (:Service {name: 'PaymentService'})-[r]-(n) RETURN n"],
        ["向量", "MATCH (n) RETURN n ORDER BY vector_distance_cosine(n.vec, $q) LIMIT 10"],
        ["全文", "MATCH (n) RETURN n ORDER BY bm25(n.text, 'retry timeout') LIMIT 10"],
      ],
      result: "排序结果",
    },
    algorithms: {
      label: "图算法",
      title: "在原图上，直接分析",
      body: "检索找到相关实体；图算法则在更广的结构中揭示重要性、社区与模式。",
      pagerankTitle: "发现关键节点",
      pagerankBody: "看见哪些实体在整个图中最为重要。",
      leidenTitle: "发现图中社区",
      leidenBody: "看见相互关联的实体如何形成连贯社区。",
      moreTitle: "不止 PageRank 与 Leiden",
      moreBody: "在同一份数据上运行更丰富的图算法。",
      moreLink: "查看图算法 →",
      carried: "与上方检索示例共享同一份图数据",
      communities: ["社区 A", "社区 B", "社区 C"],
    },
    why: {
      label: "为什么选择 NeuG",
      title: "选择合适的索引架构",
      body: "按工作负载选择 NeuG 的运行模式，或看看它如何简化原本需要拼接的多引擎架构。",
      tabs: ["NeuG 对比图数据库", "一个索引 vs 拼接式技术栈"],
      graph: {
        facts: [
          ["服务模式 · 50.6× 吞吐量", "在 14 个 LDBC SNB Interactive 复杂读取查询中，NeuG 为 617 QPS，Neo4j 为 12.2 QPS。"],
          ["嵌入模式 · 9 项中 8 项更快", "单线程 NeuG 在九个 LSQB 查询中的八个上，优于 LadybugDB 的最佳多线程结果。"],
          ["一个引擎，两种部署模式", "在进程内运行低开销分析，或将同一运行时作为服务提供给并发工作负载。"],
        ],
        note: "可复现的双模式基准测试",
        methodology: "LDBC SNB SF1 · Apple Silicon · 读取负载。服务测试：4 个客户端运行 300 秒。",
        link: "查看测试方法 →",
      },
      stack: {
        facts: [
          ["实体数据只存一份", "无需将相同实体复制到三个独立运行的数据库中。"],
          ["在一个引擎内完成融合", "结构、向量相似度与 BM25 在引擎内融合，无需跨引擎网络传输与结果拼接。"],
          ["一个一致性边界", "图、向量与全文索引始终与同一份事务数据保持一致。"],
        ],
      },
    },
    quick: {
      label: "快速开始",
      title: "从安装到第一次查询",
      body: "NeuG 与你的应用运行在一起。安装依赖、打开数据库，然后直接使用 Cypher 查询。",
      compatibility: "兼容性",
      groups: [
        ["数据格式", "Apache Arrow · Parquet"],
        ["对象存储", "S3 · OSS"],
        ["操作系统", "Linux · macOS"],
        ["处理器架构", "x86_64 · ARM64"],
      ],
      roadmap: "Windows · 路线图",
    },
    close: ["一个索引，更少组件", "从嵌入式开始，在应用需要时切换为服务模式。"],
    footer: "面向你的 Agent 应用的全能数据索引。",
  },
} as const;
