export default {
  overview: "概述",
  installation: "安装",
  getting_started: "快速入门",
  tutorials: "教程",
  data_io: "数据导入导出",
  cypher_manual: "Cypher 手册",
  storage_index: "存储索引",
  extensions: "扩展",
  transaction: "事务",
  user_clients: "客户端工具",
  reference: "API 参考",
  development: "开发指南",
  blog: { display: "hidden" },
};