export default {
  overview: "Overview",
  installation: "Installation",
  getting_started: "Getting Started",
  tutorials: "Tutorials",
  data_io: "Data I/O",
  cypher_manual: "Cypher Manual",
  storage_index: "Storage Indexes",
  extensions: "Extensions",
  transaction: "Transaction",
  user_clients: "User Clients",
  reference: "API Reference",
  development: "Development Guide",
  blog: { display: "hidden" },
};
